title: Cass Zhao
url: "casszhao.github.io/"
baseurl: "contact"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.sheffield.ac.uk/dcs/people/research-staff/cass-zhixue-zhao"
footer_text: "Postdoc Researcher @ShefNLP"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Publications"
   link: "publications"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
